// <auto-generated />
using System;
using HackathonAlert.API.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HackathonAlert.API.Core.Migrations
{
    [DbContext(typeof(AlertApiContext))]
    [Migration("20200117174025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HackathonAlert.API.Core.Domain.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AlarmId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<string>("SourceName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StreamId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TimePosted")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimePosted");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("HackathonAlert.API.Core.Domain.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<double>("Altitude")
                        .HasColumnType("double");

                    b.Property<double>("Heading")
                        .HasColumnType("double");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<long?>("ParentAlertId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Velocity")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ParentAlertId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("HackathonAlert.API.Core.Domain.Position", b =>
                {
                    b.HasOne("HackathonAlert.API.Core.Domain.Alert", "ParentAlert")
                        .WithMany("Positions")
                        .HasForeignKey("ParentAlertId");
                });
#pragma warning restore 612, 618
        }
    }
}
